spring.application.name=Cadastro
# config mysql
spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver